Created README files.
alyphen/vantage pull request #7
Opened 2023-05-22 04:26 UTC by dmccoystephenson

I've added a README for the project, as well as the frontend & backend applications.

2023-05-22 08:51 UTC, alyphen requested changes

2023-05-22 08:51 UTC, renbinden commented on frontend/README.md
> +1. Build the frontend using `npm run build`
Environment vars - .env.local?

2023-05-23 00:35 UTC, dmccoystephenson commented
Retargeted to `develop`!

2023-05-23 00:59 UTC, dmccoystephenson commented on frontend/README.md
> +1. Build the frontend using `npm run build`
Good call! Information on environment variables has been added

2023-05-24 19:43 UTC, alyphen approved these changes

2023-05-25 01:29 UTC, merged